CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Chicken                     CTTGCCCCCCCTCTAGCCCGACAAACT----CGTACCCTTAACATAAAAAACTTACCTCC
Salmon-crestedCockatoo      ----AGCCCACCCTAGCCTCACCCACT-----------ACAATNNCAAAAACCCACTACC
ScarletMacaw                ---ACGCCTACCCTAGCTCCATCAACC-----------ACAAT--TAAAAACTCACTACC
CommonCanary                ---TGCCAACCTCTAGCCCAATCGACA-----TGACCTGGAAT--AACAAAGCTACTGCA
CommonRaven                 ---TGCCAAATTCTAGCCCAACTACAT-----TGACCTGGAAT--AACAAAGCTACTACA
White-tailedEagle           ---AGCCAGCCTCTAGCCTAACCACAT--CACTAACTCATAGC--CAAGAATCACCTTTG
AfricanOstrich              ----AGCGCCCTCTAGCTCATCCACCC--------------ACTTGAACAACCCACTAAA
PeregrineFalcon             -----GCCTCCTCTAGCCCAACCACAACACC-CAAAGACTAAT--CAAAAACTCACCCCC
SnowyOwl                    ---AGCCAACCTCTAGCCTCGCCCTAA--------------ACCAGTAAAACACACTTTT
White-belliedHeron          -----------TCTAGCCCAACCCTCA-----CAACGTTTTACCTAAAAAATTCACCTAA
EmperorPenguin              ---AGCCGAACTCTAGCCCAACCACAT-ACAATTAAGAACAAT--TAAAAATTTACCTCA
MourningDove                ---AGCCCAACTCTAGCCCAACCCCCCTACAGCCAAGTATATT--TAAAAATCTACTAAA
                                        *****                                **    *    

Chicken                     CC-----CTCTTAACCAAAACATTATAAATTGTCCCAGTATAGGCGATAGAAAAGACTAC
Salmon-crestedCockatoo      TCA----CCCCTAACTAAAACATTAT-CCCCCACTTAGTATAGGCGATAGAAAAGTGCAC
ScarletMacaw                TC-----CACCCAACTAAAACATTAC-CCCCGACTTAGTATAGGTGATAGAAAAGTACAA
CommonCanary                TA-----CACCCAACTAAAGCATTTA-CT-AGTCTTAGTATAGGCGATAGAAAAGACACC
CommonRaven                 TA-----CACCAAACTAAAGCATTCA-CT-AGTCTTAGTATAGGCGATAGAAAAGACACC
White-tailedEagle           C------CCACAAACTAAAACATTCT-CC-TAACTTAGTATAGGTGATAGAAAAGTTTTC
AfricanOstrich              C------TCAAAAACTAAAACATTTT-CC-CTACTTAGTATAGGCGATAGAAAAGTTACT
PeregrineFalcon             TCCCCATCACTAAGCCAAAACATTCC-CC-TGCCTTAGTATAGGCGATAGAAAAGGCCCA
SnowyOwl                    C------CCCTCAACTAAAACATTCT-CCTCAACCTAGTATAGGCGATAGAAAAGAACCC
White-belliedHeron          T------CACTGAACTAAAGCATTAC-CC-AGACTTAGTATAGGCGATAGAAAAGACCAA
EmperorPenguin              C------CACTGAACTAAAACATTCT-CC-TGCCCTAGTATGAGCGACAGAAAAGGCACT
MourningDove                C------CACTAAACTAAACCATTCT-CC-CAACTTAGTATAGGCGATAGAAAAGACCAT
                                        * * *** ****         *  *****  * ** *******     

Chicken                     CCC-------GGCGCAATAGAGGCTAAC-TGTACCGCAAGGGAAAGA-TGAAATAGCAAT
Salmon-crestedCockatoo      CNCG------AGCGCTATAGAGA-----GAGTACCGTAAGGGAAAGAGTGAAATAGCAAT
ScarletMacaw                CCCG------GACGCCATAGAGA-----CAGTACCGTAAGGAAAAGG-TGAAATAACAAT
CommonCanary                ATT-------GGCGCGATAGAGA---CCACGTACCGTAAGGGAAAGA-TGAAATATTAGT
CommonRaven                 CATT------GGCGCGATAGAGA---TCACGTACCGTAAGGGAAAGA-TGAAATAATAAT
White-tailedEagle           CCC-------AGCGCGATAGAGA---CC-TGTACCGTAAGGGACAGA-TGAAATAATAAT
AfricanOstrich              T---------GACGCAATAGAGATATCCTTGTACCGCAAGGGAAAGA-TGAAATAATAAT
PeregrineFalcon             CT--------GGCGCAATAGAGC---TC-CGTACCGCAAGGGATAGA-TGAAATAAAAAT
SnowyOwl                    CCAG------AGCGCAATAGAGA---CTATGTACCGTAAGGGAAAGA-TGAAATAGCAAT
White-belliedHeron          CCCCCTCCCCGGCGCGATAGAGA---CC-TGTACCGTAAGGGAAAGG-TGAAATAATAGT
EmperorPenguin              AACATT----GGCGCGATAGAGG---CC-CGTACCGTAAGGGAAAGA-TGAAATAACAAT
MourningDove                CT--------GGCGCAATAGAGA---CC-CGTACCGTAAGGGAAAGA-TGAAATAGAAGT
                                        *** ******        ****** **** * **  *******  * *

Chicken                     GAAA-ACCATAAGCAAAAAACAGCAAAGACCAACCCTTGTACCTTTTGCATCATGATTTA
Salmon-crestedCockatoo      GA---AAATCAAGCACCACACAGCAAAGATTGACCCTTGTACCTCTTGCATCATGATCTA
ScarletMacaw                GA---AAGCCAAGCACGACATAGCAAAGATAGCCCCTTGTACCTTCTGCATCATGATCTA
CommonCanary                GAAATAACCTAAGCTAAAAACAGCAAAGATCAACCCTTGTACCTTTTGCATCATGGTCTA
CommonRaven                 GAAA-AAACTAAGCTATAAACAGCAAAGATCAACCCTTGTACCTTTTGCATCATGGTCTA
White-tailedEagle           GAA--AGCCCAAGCAACACGCAGCAAAGATAAACCCTTGTACCTCTTGCATCATGGTTCA
AfricanOstrich              GAA--AACCAAAGCAAAAAACAGCAAAGATCAACCCTTGTACCTTTTGCATCATGATTTA
PeregrineFalcon             GAA--ACCTCAAGCAATAAACAGCAAAGATATACCCTTTTACCTCCTGCATCATGGTTTA
SnowyOwl                    GAA--ACCCAAAGCAACAAACAGCAAAGATGAACCCTTGTACCTTTCGCATCATGATTTA
White-belliedHeron          GAA--AAACCAAGCAATAAATAGCAAAGATAGACCCTTGTACCTTTTGCATCATGGTTTA
EmperorPenguin              GAA--ACCCAAAGCAGAAAACAGCAAAGATAAATCCTTGTACCTCTTGCATCATGGTTTA
MourningDove                GAAC-AAGCCAAGCAACAAACAGCAAAGATATACCCTTGTACCTTTTGCATCATGATTTA
                            **   *    ****   *   ********     **** *****   ******** *  *

Chicken                     GCAAGAACAACCAAGCAAAGTGAGCTAAAGTTTGCCTTCCCGAAACCCAAGCGAGCTACT
Salmon-crestedCockatoo      GCAAGAACAGACAGACAAAGCGAACTTAAGCCTGCCACCCCGAAACCTAAGCGAGCTACT
ScarletMacaw                GCAAGAACAACCAGACAAAGCGAGCTTAAGCCTGCCATCCCGAAACCCAAGCGAGCTACT
CommonCanary                GCAAGAAAAACCAAGCAAAATGAATTTAAGTTTGCCATCCCGAAACCCAAGCGAGCTACT
CommonRaven                 GCAAGAAAAACCAAGCAAAATGAATTTAAGCTTGCCACCCCGAAACCTAAGCGAGCTACT
White-tailedEagle           GCAAGAATAACCAAGCAAAACGAATTTAAGCTTGCCCTCCCGAAACCCAAGCGAGCTACT
AfricanOstrich              GCAAGAACAACCAAGCAAAACGAATTTAAGCTTGCCATCCCGAAACCCAAGCGAGCTACT
PeregrineFalcon             GCAAGAACAACCAAGCAAAGCGAACTTAAGCTTGCCACCCCGAAACCCATGCGAGCTACT
SnowyOwl                    GCAAGAACAACCAAGCAAAGCGAACTTAAGCTTGCCCCCCCGAAACCCGAGCGAGCTACT
White-belliedHeron          GCAAGAACAACCAAGCAAAACGAACTTAAGCTTGTTCCCCCGAAACCCAAGCGAGCTACT
EmperorPenguin              GCAAGAATAACCAAGCAAAACGAATTTAAGCTTGCCACCCCGAAACCCGAGCGAGCTACT
MourningDove                GCAAGAACAGCCAAGCAAAGCGATCTTAAGTTTGCTATCCCGAAACCCAAGCGAGCTACT
                            ******* *  **  ****  **  * ***  **    *********   **********

Chicken                     TGCGAGCAGCTAA-AATTTGAGCGAACCCGTCTCTGTTGCAAAAGAGTGGGATGACTTGC
Salmon-crestedCockatoo      TACGAGCAGCTAC---CATGAGCAAACCCGTCTCTGTCGCAAAAGAGTGGGACGACTCGT
ScarletMacaw                CACAAGCAGCTAT---CATGAGCCAACCCGTCTCTGTTGCAAAAGAGTGGGAAGACTTGT
CommonCanary                TATGAGCAGCTAT---CTTGAGCGAACCCGTCTCTGTGGCAAAAGAGTGGGATGACTTGT
CommonRaven                 TGTGAGCAGCTAT-T--TTGAGCGAACCCGTCTCTGTTGCAAAAGAGTGGGATGACTTAC
White-tailedEagle           TATAGGCAGCTAC-TCCCTGAGCGAACCCGTCTCTGTTGCAAAAGAGTGGGACGACCTAT
AfricanOstrich              TACAAGCAGCTAT-TA-TTGAGCAAACCCGTCTCTGTGGCAAAAGAGTGGGAAGACTTGT
PeregrineFalcon             TACAAGCAGCTGC-CC-CCGAGCGAACCCGTCTCTGTTGCAAAAGAGTGGGACGACTTGT
SnowyOwl                    TGCAGGCAGCTGCATTACCGAGCGAACCCGTCTCTGTCGCAAAAGAGTGGGATGACTTGC
White-belliedHeron          TATAGGCAGCTAT----TTGAGCGAACCCGTCTCTGTTGCAAAAGAGTGGGACGACCTAT
EmperorPenguin              TACAAGCAGCTAC-CCCCTGAGCGAACCCGTCTCTGTTGCAAAAGAGTGGGACGACTTGT
MourningDove                TACAAGCAGCTAT-CC-TTGAGCGAACCCGTCTCTGTTGCAAAAGAGTGGGACGACTTGT
                                 ******        **** ************* ************** ***    

Chicken                     CAGTAGAGGTGAAAAGCCTACCGAGCTGGGTGATAGCTGGTTACCTGTCAAACGAATCTA
Salmon-crestedCockatoo      CAGTAGAGGTGAAAAGCCAACCGAGCTAGGTGATAGCTGGTTGCCCGCAAAATGAATCTT
ScarletMacaw                TAGTAGAGGTGAAAAGCCAACCGAGCTGGGTGATAGCTGGTTGCCTGCAAAACGAATCTA
CommonCanary                TAGTAGAGGTGAAAAGCCAATCGAGCTGGGTGATAGCTGGTTGCCTGTGAAACGAATCTT
CommonRaven                 TAGTAGAGGTGAAAAGCCAATCGAGCTGGGTGATAGCTGGTTGCCTGTGAAACGAATCTT
White-tailedEagle           TAGTAGAGGTGAAAAGCCAACCGAGCTGGGTGATAGCTGGTTGCCTGTAAAACGAATCTA
AfricanOstrich              CAGTAGAGGTGAAAAGCCAACCGAGCTGGGTGATAGCTGGTTGCCTGTGAAAAGAATCTA
PeregrineFalcon             CAGTAGAGGTGAAAAGCCAACCGAGCTGGGTGATAGCTGGTTACCTGCAAAACGAATCTA
SnowyOwl                    CAGTAGAGGTGAAAAGCCTATCGAGCCGAGTGATAGCTGGTTGCCTGTGAAACGAATCTA
White-belliedHeron          TAGTAGAGGTGAAAAGCCAATCGAGCTGGGTGATAGCTGGTTGCCCGTGAAATGAATCTG
EmperorPenguin              CAGTAGAGGTGAAAAGCCAACCGAGCCGGGTGATAGCTGGTTGCCTGTGAAGTGAATCTA
MourningDove                TAGTAGAGGTGAAAAGCCAACCGAGCTGGGTGATAGCTGGTTACCTGTGAAATGAATCTA
                             ***************** * *****   ************* ** *  **  ****** 

Chicken                     AGTTCCCCCTTAACCCACCCCCT--AAAGACACCCACCTTTGTCAACCTTGAGAACGTTG
Salmon-crestedCockatoo      AGTTCTTCCTTAACC---CCTCTCCCAGGACAACCAACCCAAAC----CCCCACGCAGCG
ScarletMacaw                AGTTCCCCCTTAACCCT-CTTTTTCCTCCCCAGACAAACCCAAC----CCAAATGTGATA
CommonCanary                AGTTCACTCTTAATT---CTTCT--CCAAGGAAATACA-CGAAC----CCTAATGAAGCG
CommonRaven                 AGTTCACTCTTAATT---CTTCT--CCAAGGAAACTAACAGAAC----CCTAATGAAGCG
White-tailedEagle           AGTTCACCCTTAATT---CCTCT--CCAAGGACCCCCAGCAAGC----CCGCACGTAGAG
AfricanOstrich              AGTTCACTCCTAACTTA-CCCCT--CCCGGCATCCA---CTAAC----CTTAATGAGGAA
PeregrineFalcon             AGTTCACCCTTAGTCT--CTCCC--TCAAGGACCCCAATCAACC----CAAATTGAAATG
SnowyOwl                    AGTTCCCCCTTAGCCCCCCTCCCTGCCCGACACATAA-----------CCTAACATGAGA
White-belliedHeron          AGTTCTACCTTAACTTACCCCAT--CAATGAATTTCAACTGACCACCTCTAATTGTGGGA
EmperorPenguin              AGTTCCCTCTTAATTTTCCCCCT--CCGGACACCCACCCTCAAC----CACCATGTGGTA
MourningDove                AGTTCTGCCTTGACAA--CCCCT--CCAAGAACCCTAAGCCACC----CTAA-TGAGAGC
                            *****   * *       *            *                            

Chicken                     GGGTTAAGAGCAATTCGATGGGGGTACAGCTCCATCGAAAAAGAACACAACCTCCTCCAG
Salmon-crestedCockatoo      GG-TTAAGAGCTATCTAAAGGGGGTACAGCCCCTTTAAAGANGGACACACCCTCCACTAG
ScarletMacaw                G--TTAAGGGCTATTTAAAGGGGGTACAGCCCCTTTAAAAAAGGACACAACCTCCACCAG
CommonCanary                AA-TTAAGGGCAATTTAAAGGGGGTACAGCTCCTTTAAAAAAGAATACAATCTCCACGAG
CommonRaven                 AA-TTAAGGGCAATTTAAAGGGGGTACAGCTCCTTTAAAAAAGAATACAATCTCTACGAG
White-tailedEagle           AA-TTAAGAGCAACCTAAAGGAGGTACAGCTCCTTTAAAAAAGGATATAGCCTCTCGCAG
AfricanOstrich              AG-CTAGGAACTATTTAAAGGAGGTACAGCTCCTTTAAAAAAGAACACAACCTCCATTAG
PeregrineFalcon             AG-CTAAGAGCTATCTAAAGGGGGTACAGCTCCTTTAATAAAGAATACAGCCTTCATTAG
SnowyOwl                    GGACTAAGAGCTCTTTAAAGGAGGTACAGCCCCTTTAAAACAGGATACAACCTTCATTAG
White-belliedHeron          AG-TTAAGAGCAATTTAAAGGAGGTACAGCCCCTTTAAAAAAGAATACAACCTCCCCTAG
EmperorPenguin              GA-TCAAGAGTAATTTAAAGGGGGTACAGCCCCTTTAAAAAAGAATACAACCTCCACTAG
MourningDove                AG-TCAAGAGTAATTTAAAGGGGGTACAGCCCCTTTAAAACAGAATACAACCTCCCCTAG
                                 * *         * ** ******** ** *  *    * * * *  **     **

Chicken                     CGGATAATA-ATCACCCCCCCCCGCAC---TGTGGGCCTTCAAGCAGCCACCAACAAAAG
Salmon-crestedCockatoo      CGGATAATC-CCTCCCCACCTTAGCCCCCNNGTGGGCCTTAAAGCAGCCATCCAA-AAAG
ScarletMacaw                CGGATAAC--CCCTGTACGCCCAACCC---CGTGGGCCTTAAAGCAGCCACCCCC-AAAG
CommonCanary                CGGATAAATAATATTCCCCGACTATAC---TGTGGGCCCTCAAGCAGCCATCAAC-AAAG
CommonRaven                 CGGATAAAT-AATCTATAGAAAGATCTCC-TGTGGGCCCTCAAGCAGCCATCAAC-AAAG
White-tailedEagle           CGGATAATT-TAACTCACCCCCAACT----TGTAGGCCTTTAAGCAGCCACCAAC-AAAG
AfricanOstrich              AGGGTAACC-CCCCCCCCCCCCTCCTCCCACGTTGGCCCTAAAGCAGCCATCAAC-AAAG
PeregrineFalcon             CGGATAACT-TATAAAGCTTTAAAAAT---TGTAGGCCCTCAAGCAGCCACCAAC-AAAG
SnowyOwl                    AGGATAACA-CCCCACTACTACCCTAC---AGTAGGCCTTCAAGCAGCCACCAGT-AAAG
White-belliedHeron          CGGATAAAA-TCCCCCTTCCCCACTCC---TGTAGGCTTTAAAGCAGCCAACAAT-AAAG
EmperorPenguin              CGGATAACTGCCCAACTGACACTAAAC---TGTGGGCCCTCAAGCAGCCATCAAC-AAAG
MourningDove                CGGATAACT-CACCCTACAAACAACAT---TGTGGGCCTTCAAGCAGCCATCAAC-AGAG
                             ** ***                        ** ***  * ********* *    * **

Chicken                     AGTGCGTCAAAGCTCCCTCATTA---AAAAATCTAAAACCCTATTTGACTCCCTCAACCA
Salmon-crestedCockatoo      AGTGCGTCAAAGCTCTCAACC-----AAAAATATAA-AAATAATGTGACTCCCTACATCC
ScarletMacaw                ATTGCGTCAAAGCTCCATCAACCA--AAAACCCCCAAAACCAATGCGACTCCCTACACCC
CommonCanary                AGTGCGTTAAAGCTCTACTCCAT---AAAAATATAA-GAACAATATGACTCCCTCA-TCA
CommonRaven                 AGTGCGTTAAAGCTCTTCGACTA---AAAAATATAA-GAACTTCATGACTCCCTCA-TCA
White-tailedEagle           AGTGCGTCAAAGCTCCCTTCCC----AAAGATATAA-AAACAACATGACTCCCTCC-CTA
AfricanOstrich              AGTGCGTCAAAGCTCAACCAAAT---AAAAATTCAA-TAACACTATGACCCCCTACACCA
PeregrineFalcon             AGTGCGTCAAAGCTCCACGTAA----AAAAATACAA-AAGCAGCACGACTCCCTTCAAAA
SnowyOwl                    AATGCGTCAAAGCTCTCACCAC----AAAAATCCAACAGATAACATGACTCCCTTC-TCA
White-belliedHeron          AATGCGTCAAAGCTCACTCACCT---AAAAATCCAA-AGACATCATGACTCCCTTA-CCC
EmperorPenguin              AGTGCGTCAAAGCTCTACGCCTAA--AAAAATCCAA-AAACAACAGGACTCCCTTA-TCC
MourningDove                AGTGCGTCAAAGCTCCACCCCTCACAAAAAATCCCA-AAACCCCATGACTCCCTTC-CCA
                            * ***** *******           ***      *          *** ****      

Chicken                     A-AGCAGGTTAACCTAT-GAC-AATAGAAGAATCAATGCTAAAATGAGTAATCTGGAACC
Salmon-crestedCockatoo      CTAGCTGGCTAACCTAT-AAC-AATAGATGAACTAATGCTAGAACGAGTAACCAGGATAT
ScarletMacaw                ACAGCAGGCCAACCTAT-AAC-AATAGATGAATCAATGCTAGAACGAGTAACCAGGACAC
CommonCanary                TTAACAGGCTAACCTATATTTAAATAGGAGAATTAATGCTAGAATGAGTAACCTGGGTCC
CommonRaven                 TTAACAGGCTAACCTATATGTAAATAGGAGAATTAATGCTAGAATGAGTAACCAGGGTCC
White-tailedEagle           CTAACAGGCCAACCTAT-CAC-AATAGGAGAATCAATGCTAGAATGAGTAACTAGGACCC
AfricanOstrich              CTAACAGGCCAATCTAT-GAC-CATAGAAGAACTTATGCTAAAATGAGTAATTAGAAATT
PeregrineFalcon             CTAGCAGGTCAATCTATAAAC-AATAGAAGAGCTAATGCTAAAATGAGTAACTAGGTAGC
SnowyOwl                    CTAACAGGCCAATCTATAGAC--ATAGAAGAATTAATGCTAAAATGAGTAACCTGGGCCC
White-belliedHeron          CTAACGGGCTAACCTAT--ACCTATAGGAGAATTAATGCTAAAATAAGTAACTTAGAGCC
EmperorPenguin              ATAACAGGCCAACCTAT-GAC-AATAGGAGAATCAATGCTAAAATGAGTAATCAGGGACT
MourningDove                CTAACAGGTTAACCTAT-GAC-CATAGGAGAATTAATGCTAAAATGAGTAACTAGGGCAT
                              * * **  ** ****      ****  **    ****** **  *****         

Chicken                     TATC--CTCCTACGGCGTAAACTTACAT-TAATACATTATTAACAGAACTCA-ACTTATA
Salmon-crestedCockatoo      CCT---CCCCTCAAGCGCTAGTTTACAC-------ATCATTAACAGNNTCCT-ACCATCA
ScarletMacaw                TACGT-CCCCCCAAGCGCCAGCCTGTAT-------ACCATTAACAG---------TAAAA
CommonCanary                TC----CCTCTACGACGCAAGCTTACAT-CGGCACATTATTAACAAATC----ACCAATA
CommonRaven                 TC----CCTCTACGACGCAAGCTTACAT-CTTTACATTATTAACAAATC----ACCAAGA
White-tailedEagle           CCCT--CCTCTCAAGCGCAAACTTACAT-TACCACATTATTAACAGCATTTA-ATTAATA
AfricanOstrich              CT----TCTCTAAAGCGCAAGCTTACAT--TATATATTATTAACAGCCTA---ACTTATA
PeregrineFalcon             CTACTACCTCTCGAGCGCAAACTTAGCA-ACAAGTACCATTAACAGAAAA---ATTAATG
SnowyOwl                    TC----CCTCTCAAGCGCAAGCTTACATTCCCCACATTATTAACAGGCCAGAGCCTAATA
White-belliedHeron          CCGCCTCCTCTCAGACGCAAACTTACAT-CCCTCAATTATTAACAGATCA---ACCAATA
EmperorPenguin              AC----CCTCTCGAGCGCAAGCTTACAT-TACCCCATTATTAACAAACCCCAGACTAATA
MourningDove                ACC---CCTCTCAAGCGCAAACTTACATCTCCCCCATTATTAACAGACA----ACTAATA
                                     *     **  *   *           *  *******               

Chicken                     --CCCCCACACTAA------CAAG-CAATACGTATTCCTCAATCTGTTAAGCCAACCCAG
Salmon-crestedCockatoo      ATGCTCAGCCCCAACNNNCCCAAGACCAAACATTGCACATACCCTGTTAACCCAACCCAG
ScarletMacaw                --CCTCAATAATAA------CCACCCCCACCATTGAACCCACCCTGTCAACCCAACTCAG
CommonCanary                TACGATAAATCAAA------CAAG-CAGAGTATTAGGT--ACATTGTTAACCCGACAGAG
CommonRaven                 TACGACAAATCAAA------CAAG-CAGAGTATCAGGT--AAATTGTTAACCCGACAGAG
White-tailedEagle           --CCACAATCTCAA------CAAGTCCGCACATTAAAACTACCCTGTTAACCCAACACAG
AfricanOstrich              --TTTACACTCCTA------CTAGAACAAATATAAAACC-ACTCTGTTAACCCAACTCAG
PeregrineFalcon             T-CCCCAACCACAA------CAAGACCAAACATTCTAGT-ACACTGTTAACCCAACCCAG
SnowyOwl                    TGCCCAAACCCGAA------CAAGAATAAAGTATTAACCAACCCTGTTAACCCAACCCAG
White-belliedHeron          --CTACAACCCCTA------CAAGCCTAAATATTGACCT--TTCTGTTACCCCAACACCG
EmperorPenguin              C-TTCCAACTCAAA------CAAG-CCAAGTATTAAATCCACCCTGTTAATCCAACTCAG
MourningDove                --CTCTCACTCCAA------CAAGACCATGTATTTTACC--CCCTGTTAACCCAACTCAG
                                         *      * *                     *** *  ** **   *

Chicken                     GAGCGCCC---AC--AGGATGATTAAAACCTACAGAAGGAACTCGGC-AAAC--CAAAGA
Salmon-crestedCockatoo      GAGCGCGCNNNACT-AGGACGATTAAAACCTACAAAAGGAACTCGGC-AAAC--TCAGGG
ScarletMacaw                GGGCGCAC---ACT-GGAGTGATCAAAATCTACAAAAGGAACTCGGC-AAAC--CTAAGA
CommonCanary                GAGCGTCC---ATTAAGAAAGATTAAAACCTGTAAAAGGAACTCGGC-AAATCGTCAAGG
CommonRaven                 GAGCGTCC---ATTAAGAAAGATTAAAACCTGTAAAAGGAACTAGGCAAACACATCAAGG
White-tailedEagle           GAGCGCCC---ACT-AGAAAGACTAAAATCTGTAAAAGGAACTAGGC-AAAC--CCAAGG
AfricanOstrich              GAGCGCCT---ATT-AGAAAGATTAAAATCTGCAAAAGGAACTAGGC-AAAC--CCAAGG
PeregrineFalcon             GTGCGCCC---ATT-AGAAAGATTAAAATCTGTAAAAGGAATTCAGC-AAAC--ACAAGG
SnowyOwl                    GAGCGCCT---GCT-AGAAAGATTTAAATCTGTAAAAGGAACTAGGC-AAAC--CCAAGG
White-belliedHeron          GAGCGCCC---ATTAAGAAGGATTAAAATCTGTAAAAGGAACTAGGC-AAAC--CCAGGG
EmperorPenguin              GTGCGCCC---ATC-AGAAAGATTCAAATCTGCAAAAGGAACTAGGC-AACC--CCAAGG
MourningDove                GAGCGCCC---ACT-AGAAAGATTAAAATCTGTAAAAGGAACTAGGCAAATC--CTAAGG
                            * ***           *   **   *** **  * ****** *  ** **      * * 

Chicken                     CCCGACTGTTTCCCAAAAACATAGCCTTCAGCTAACAA------CAAGTATTGAAGGTGA
Salmon-crestedCockatoo      CCCGACTGTTTACCAAAAACATAGCCTTCAGCCA--AA------CAAGTATTGAAGGTGA
ScarletMacaw                TCCGACTGTTTACCAAAAACATAGCCTTCAGCCA--AA------CAAGTATTGAAGGTGA
CommonCanary                CCCGACTGTTTACCAAAAACATAGCCTTCAGCAA--ACCACAGACAAGTATTGAAGGTGA
CommonRaven                 CCCGACTGTTTACCAAAAACATAGCCTTCAGCAA--ACAACAAACAAGTATTGAAGGTGA
White-tailedEagle           CCCGACTGTTTACCAAAAACATAGCCTTCAGCAA--AC------CAAGTATTGAAGGTGA
AfricanOstrich              CCCGACTGTTTACCAAAAACATAGCCTTCAGCCAATAA------CAAGTATTGAAGGTGA
PeregrineFalcon             CCCGACTGTTTACCAAAAACATAGCCTCCAGCCT--AA------CAAGTATTGGAGGTGA
SnowyOwl                    CCCGACTGTTTACCAAAAACATAGCCTTCAGCAC--AC------CAAGTATTGAAGGTGA
White-belliedHeron          CCCGACTGTTTACCAAAAACATAGCCTTCAGCCA--AC------CAAGTATTGAAGGTGA
EmperorPenguin              CCCGACTGTTTACCAAAAACATAGCCTTCAGCCA--AC------CAAGTATTGAAGGTGA
MourningDove                CCCGACTGTTTACCAAAAACATAGCCTTCAGCTG--AA------CAAGTATTGAAGGTGA
                             ********** *************** ****    *       ********* ******

Chicken                     TGCCTGCCCAGTGACCCCCA-AAGTTCAACGGCCGCGGTATCCTAACCGTGCGAAGGTAG
Salmon-crestedCockatoo      TGCCTGCCCGGTGACATCACNNNGTTCAACGGCCGCGGTATCCTAACCGTGCAAAGGTAG
ScarletMacaw                TGCCTGCCCAGTGACACCAT---GTTTAACGGCCGCGGTATCCTAACCGTGCAAAGGTAG
CommonCanary                TGCCTGCCCGGTGACT-CAC---GTTTAACGGCCGCGGTATCCTAACCGTGCAAAGGTAG
CommonRaven                 TGCCTGCCCTGTGACTTAGT---GTTTAACGGCCGCGGTATCCTAACCGTGCAAAGGTAG
White-tailedEagle           CGCCTGCCCAGTGACCTCTG---GTTCAACGGCCGCGGTATCCTAACCGTGCGAAGGTAG
AfricanOstrich              TGCCTGCCCAGTGACT-AAT---GTTTAACGGCCGCGGTATCCTAACCGTGCGAAGGTAG
PeregrineFalcon             TGCCTGCCCAGTGACACTAC---ATTCAACGGCCGCGGTATCCTAACCGTGCAAAGGTAG
SnowyOwl                    CGCCTGCCCAGTGACACTAC---GTTCAACGGCCGCGGTATCCTAACCGTGCAAAGGTAG
White-belliedHeron          TGCCTGCCCAGTGACA-CAC---GTTCAACGGCCGCGGTATCCTAACCGTGCGAAGGTAG
EmperorPenguin              TGCCTGCCCAGTGACACCAT---GTTCAACGGCCGCGGTATCCTAACCGTGCGAAGGTAG
MourningDove                TGCCTGCCCAGTGACCCCAT---GTTCAACGGCCGCGGTATCCTAACCGTGCAAAGGTAG
                             ******** *****         ** ************************* *******

Chicken                     CGCAATCAATTGTCCCGTAAATTGAGACTTGTATGAATGGCTAAACGAGGTCTTAACTGT
Salmon-crestedCockatoo      CGCAATCAATTGTCCCATAAATCGAGACTTGTATGAATGGCTAAACGAGGCCCTAACTGT
ScarletMacaw                CGCAATCAATTGTCCCATAAATCGAGACCTGTATGAATGGCTAAACGAGGTCTTAACTGT
CommonCanary                CGCAATCAATTGTCCCATAAATCGAGACTAGTATGAATGGCTAAACGAGGTCTTAACTGT
CommonRaven                 CGCAATCAATTGTCTCATAAATCGGGACCCGTATGAATGGCTAAACGAGGTCTTAACTGT
White-tailedEagle           CGCAATCAATTGTCTCATAAATCGGGACTTGTATGAATGGCTAAACGAGGCCTTAACTGT
AfricanOstrich              CGCAATCAATTGTCCCATAAATCGGGACTTGTATGAATGGCTAAACGAGGTCTCAACTGT
PeregrineFalcon             CGCAATCAATTGTCTCATAAATCGGGACCTGTATGAATGGCTAAACGAGGTCTTAACTGT
SnowyOwl                    CGCAATCAATTGTCCCATAAATCGAGACCTGTATGAACGGCCAAACGAGGTCTTAACTGT
White-belliedHeron          CGCAATCAATTGTCCCATAAATCGAGACTTGTATGAATGGCTAAACGAGGTCCTAACTGT
EmperorPenguin              CGCAATCAATTGTCCCATAAATCGAGACTTGTATGAATGGCTAAACGAGGTCTTAACTGT
MourningDove                CGCAATCAATTGTCCCATAAATCGAGACTTGTATGAATGGCTAAACGAGGTCTTAACTGT
                            ************** * ***** * ***  ******* *** ******** *  ******

Chicken                     CTCCTGTAGGTAATCTATGAAATTAGTATTCCCGTGCAAAAACGAGAATGTGAACATAAG
Salmon-crestedCockatoo      CTCCTGTAGGCAATCAGTGAAACTGATCCCCCCGTGCAAAAGCGGGAATAAATACACAAG
ScarletMacaw                CTCCTGTAGACAATCGGTGAAACTGATCTCTCTGTGCAAAAGCAGAGATAAACACATAAG
CommonCanary                CTCTTACAGGCAATCGGTGAAATTGATCTCCCTGTACAAAAGCAGGGATAAACACATAAG
CommonRaven                 CTCTTACAGGCGATCGGTGAAATTGATCTCCCTGTGCAAAAGCAGGGATAACTACATAAG
White-tailedEagle           CTCTTACAGATGGTCAGTGAAATTGATCTTCCTGTGCAAAAGCAGGAATATACACATAAG
AfricanOstrich              CTCTTGCAGATAATCAATGAAATTGATCTTCCTGTGCAAAAGCAGGAATATAAACATAAG
PeregrineFalcon             CTCTTACAGATAATCAGCGAAATTGATCTTCCTGTGCAAAAGCAGGAATAAGCACATAAG
SnowyOwl                    CTCTTACAGATAATCAGTGAAATTGATCTCCCTGTGCAAAAGCAGGGATACACCCACAAG
White-belliedHeron          CTCTTACAGATAATCAGTGAAATTGATCTTCCTGTGCAAAAGCAGGAATCACCACATAAG
EmperorPenguin              CTCTTGCAGACAATCAATGAAATTGATCTTCCTGTGCAAAAGCAGGAATAAGCCCATAAG
MourningDove                CTCTTACAGATAATCAGTGAAATTGATCTCCCTGTGCAAAAGCAGGAATGTGAACATAAG
                            *** *  **    **   **** *  *    * ** ***** *    **     ** ***

Chicken                     ACGAGAAGACCCTGTGGAACTTTAAAATCA-CGACCACCTTACAACCTTACACAG--CCC
Salmon-crestedCockatoo      ACGAGAAGACCCTGTGGAACTTTAAAATCAATAGCCACTACAC-ACCAACCCAAANNGCC
ScarletMacaw                ACGAGAAGACCCTGTGGAACTTCAAAATCAATAGCCACCCCAC---CCAACTTACCAACC
CommonCanary                ACGAGAAGACCCTGTGGAACTTTAAAACCAGCAACCACCTTAA-AACACATACAC--ACC
CommonRaven                 ACGAGAAGACCCTGTGGAGCTTAAAAATCAGCAGCCACCCCTC-CACACATTCAC--ACC
White-tailedEagle           ACGAGAAGACCCTGTGGAACTTAAAAATCAGCAGCCACTATAC--ACAAATGTAC--ACC
AfricanOstrich              ACGAGAAGACCCTGTGGAACTTAAAAACCAAGGATCAATGCAC--TCCCACCCAA--ACC
PeregrineFalcon             ACGAGAAGACCCTGTGGAACTTAAAAATCAATGGCCATCACGC-ACCAAACTCAA--ACC
SnowyOwl                    ACGAGAAGACCCTGTGGAACTTAAAAATCAATGGCCACCACCC-AAAAACCCTAC--CCC
White-belliedHeron          ACGAGAAGACCCTGTGGAACTTTAAAATCAGCGGCCACCCCACAAACAACCCAAA--CCC
EmperorPenguin              ACGAGAAGACCCTGTGGAACTTAAAAATCAGCGACCACTACAC--ACAACCCAAA--ACC
MourningDove                ACGAGAAGACCCTGTGGAACTTAAAAATCAGCAGCCACCCCATAACAAAGCCCA---ACC
                            ****************** *** **** **     **                *    **

Chicken                     CACT-----GGGTCCACCCACACATA--AACCCCTGGTCGACA-TTTTTCGGTTGGGGCG
Salmon-crestedCockatoo      CACTC----GGCCCCACTACNNCCG---TAACACTGGCTAACA-TTTTTAGATTGGGGCA
ScarletMacaw                CACC-----AGGCCCACCACCTA-----AGACACTGGCTAACA-TTTTTAGGTTGGGGCG
CommonCanary                CACC-----GGGTTCACTGACACATA--AGATACTGGTCTGCG-TTTTTCGGTTGGGGCG
CommonRaven                 CACC-----GGGTACACGCTTATACA--GGGAACTGGCCTGCA-TTTTTCGGTTGGGGCG
White-tailedEagle           TACT-----AGGCCTACGCCTAAAACCTAAATGCTGGCCTGCA-TTTTTCGGTTGGGGCG
AfricanOstrich              TACTA----AGGCTCACCACTCCTGCA-ACCAACTGATCCTCG-TTTTTTGGTTGGGGCG
PeregrineFalcon             TACC-----AGGCACACTATCCCTCGC--AACATTGGCTCATAATTTTTCGGTTGGGGCA
SnowyOwl                    TTCCCCAGAAGAACCCCCAACACCACC-AAGCACTGGCCACTA-TTTTTCGGTTGGGGCG
White-belliedHeron          TACT-----GGATCTATTACCCTA----AAACGCTGGCCCGCA-TTTTTCGGTTGGGGCG
EmperorPenguin              TACC-----AGGCCCACAACCCCAACA-ACACACTGGCCCGCA-TTTTTCGGTTGGGGCG
MourningDove                TACC-----AGGCCCAC--CTTCAACA-AAACTCTGGCTCGCATTTTTTCGGTTGGGGCG
                              *       *                       **        ***** * ******* 

Chicken                     ACCTTGGAGAAAAAAAAATCCTCCAAACCCACAGACCA-CAACTCTTCACTAAGACCAAC
Salmon-crestedCockatoo      ATCTTGGAGAAAAACAAATCCTCCAAAAACA-AGGCCA-AACCCCTTAGCAAAGAGCTAC
ScarletMacaw                ACCTTGGAGAAAAACAGACCCTCCAAAAACA-GGGCCA-AACCCCCTAACTAAGAGCAAC
CommonCanary                ACCTTGGAGTAAAACAAAACCTCCAAAAATT-AGACCA-AACCTCTAGACTGAGAGCAAC
CommonRaven                 ACCTTGGAGAAAAACAAATCCTCCAAAAATT-AGACCA-CAACTCTAGACTGAGAGCGAC
White-tailedEagle           ACCTTGGAGAAAAGAAAAACCTCCAAAAATA-AGAACA-TACCCCTTAACCAAGAGCAAC
AfricanOstrich              ACCTTGGAGAAAAAAGAATCCTCCAAAAACA-AGACCA-CAACTCTTAACTAAGAGCCAC
PeregrineFalcon             ACCTTGGAGTAAAACATACCCTCCAAAAATA-AGACAA-CCCATCTTAACCAAGAACCAC
SnowyOwl                    ACCTTGGAGAAAAACAAACCCTCCAAAACAA-AGACCA-CACCTCTTGACCAAGAACATC
White-belliedHeron          ACCTTGGAGAAAAACAAATCCTCCAAAAACA-AGACCA-CACCTCTTAACCAAGAGCAAC
EmperorPenguin              ACCTTGGAGAAAAACAGATCCTCCAAAAATA-AGACTA-CACCTCTTAACCAAGAGCGAC
MourningDove                ACCTTGGAGAAAAACACACCCTCCAAAAACA-AGACCACCACCTCTTAACTAAGAGCAAC
                            * ******* ***    * ********      *   *      *    *  *** *  *

Chicken                     TCCTCAAAGTACCAACAGTAACCAGACCCAAT-ATAATTGAGCAATGGACCAAGCTACCC
Salmon-crestedCockatoo      CCCTCAACGCACTAACAGTACCCAGATCCAAT-AAAATTGACCAATGAACCAAGCTACCC
ScarletMacaw                CTCTCAACGTGCCAACAGCACCCAGACCCAGT-AGACCTGATCAATGGACCAAGCTACCC
CommonCanary                CCCTCAACGTGCTAATAGCATCCAGACCCAAT-ACAATTGATCAATGGACCAAGCTACCC
CommonRaven                 CCCTCAACGTGCGAATAGCACCCAGACCCAAT-ATAATTGATCAATGGACCAAGTTACCC
White-tailedEagle           CCCTCAACGTACTAATAGTACCCAGATCCAATAAATATTGATCAATGGACCAAGCTACCC
AfricanOstrich              TCCTCAAAGTGCCAACAGCGACCAGACCCAAT-ATAATTGATTAATGGACCAAGCTACCC
PeregrineFalcon             CCATCAACGTGCAAACAGCAACCAGACCCAAC-ACAGTTGAACAATGGACCAAGCTACCC
SnowyOwl                    ACCTCAACGTACTAACAGTAACCAGACCCAATAACAATTGAGCAATGAACCAAGCTACCC
White-belliedHeron          ATCTCTACGTGCTAACAGCAACCAGACCCAAT-ACAATTGACCAATGAACCAAGCTACCC
EmperorPenguin              ACCTCAACGTACTAACAGTAACCAGACCCAAT-ATAATTGACCAATGGACCAAGCTACCC
MourningDove                CCCTCAACGTACTAATAGTGACCAGACCCAAT-ATAATTGACCAATGGACCAAGCTACCC
                               ** * *  * ** **   ***** ***   *    ***  **** ****** *****

Chicken                     CAGGGATAACAGCGCAATCTCCTCCAAGAGCCCATATCGACAAGGAGGTTTACGACCTCG
Salmon-crestedCockatoo      CAGGGATAACAGCGCAATCTCCCCCAAGAGTCCCTATCGACGAGGAGGTTTACGACCTCG
ScarletMacaw                CAGGGATAACAGCGCAATCTCCCCCAAGAGCCCCTATCGACGGGGAGGTTTACGACCTCG
CommonCanary                CAGGGATAACAGCGCAATCTCCTTCGAGAGTCCATATCGACGAGGAGGTTTACGACCTCG
CommonRaven                 CAGGGATAACAGCGCAATCTCCTCCGAGAGTCCGTATCGACGGGGAGGTTTACGACCTCG
White-tailedEagle           CAGGGATAACAGCGCAATCTCTCCTAAGAGCCCTTATCGACGGAGGGGTTTACGACCTCG
AfricanOstrich              CAGGGATAACAGCGCAATCTCCTTCAAGAGCCCCTATCGACAAGGAGGTTTACGACCTCG
PeregrineFalcon             CAGGGATAACAGCGCAATCTCTCCCAAGAGCCCCCATCGACGGAGAGGTTTACGACCTCG
SnowyOwl                    CAGGGATAACAGCGCAATCCCCTCCAAGAGCCCCTATCGACGAGGGGGTTTACGACCTCG
White-belliedHeron          CAGGGATAACAGCGCAATCTCCTTCAAGAGCCCATATCGACAAGGAGGTTTACGACCTCG
EmperorPenguin              CAGGGATAACAGCGCAATCCCCTCCAAGAGCTCATATCGACGAGGGGGTTTACGACCTCG
MourningDove                CAGGGATAACAGCGCAATCCCCTCCAAGAGCCCATATCGACAAGGGGGTTTACGACCTCG
                            ******************* *     ****  *  ******   * **************

Chicken                     ATGTTGGATCAGGACAACCTAATGGTGCAACCGCTATTAAGGGTTCGTTTGTTCAACGAT
Salmon-crestedCockatoo      ATGTTGGATCAGGACATCCTAGTGGTGCAGCCGCTACTAAGGGTTCGTTTGTTCAACGAT
ScarletMacaw                ATGTTGGATCAGGACATCCTAGTGGTGCAGCCGCTACTAAGGGTTCGTTTGTTCAACGAT
CommonCanary                ATGTTGGATCAGGACATCCTAGTGGTGCAGCCGCTACTAAGGGTTCGTTTGTTCAACGAT
CommonRaven                 ATGTTGGATCAGGACATCCTAGTGGTGCAGCCGCTACTAAGGGTTCGTTTGTTCAACGAT
White-tailedEagle           ATGTTGGATCAGGACATCCTAATGGTGCAGTCGCTATTAAGGGTTCGTTTGTTCAACGAT
AfricanOstrich              ATGTTGGATCAGGACATCCTAATGGTGCAGCCGCTATTAAGGGTTCGTTTGTTCAACGAT
PeregrineFalcon             ATGTTGGATCAGGACATCCCAATGGTGCAGCCGCTATTAAGGGTTCGTTTGTTCAACGAT
SnowyOwl                    ATGTTGGATCAGGACATCCTAATGGTGCAGCCGCTATTAAGGGTTCGTTTGTTCAACGAT
White-belliedHeron          ATGTTGGATCAGGACATCCTAATGGTGCAGCCGCTATTAAGGGTTCGTTTGTTCAACGAT
EmperorPenguin              ATGTTGGATCAGGACATCCTAATGGTGCAGCCGCTATTAAGGGTTCGTTTGTTCAACGAT
MourningDove                ATGTTGGATCAGGACATCCTAATGGTGCAGCCGCTATTAAGGGTTCGTTTGTTCAACGAT
                            **************** ** * *******  ***** ***********************

Chicken                     TAACAGTCCTACGTGATCTGAGTTCAGACCGGAGCAATCCAGGTCGGTTTCTATCTATGG
Salmon-crestedCockatoo      TAACAGTCCTACGTGATCTGAGTTCAGACCGGAGCAATCCAGGTCGGTTTCTATCTGT-G
ScarletMacaw                TAACAGTCCTACGTGATCTGAGTTCAGACCGGAGCAATCCAGGTCGGTTTCTATCTAT-G
CommonCanary                TAACAGTCCTACGTGATCTGAGTTCAGACCGGAGTGATCCAGGTCGGTTTCTATCTAT-G
CommonRaven                 TAATAGTCCTACGTGATCTGAGTTCAGACCGGAGCAATCCAGGTCGGTTTCCATCTAT-G
White-tailedEagle           TAACAGTCCTACGTGATCTGAGTTCAGACCGGAGCAATCCAGGTCGGTTTCTATCTAT-G
AfricanOstrich              TAACAGTCCTACGTGATCTGAGTTCAGACCGGAGAAATCCAGGTCGGTTTCTATCTAT-G
PeregrineFalcon             TAACAGTCCTACGTGATCTGAGTTCAGACCGGAGCAATCCAGGTCGGTTTCTATCTAT-G
SnowyOwl                    TAACAGTCCTACGTGATCTGAGTTCAGACCGGAGCAATCCAGGTCGGTTTCTATCTGT-G
White-belliedHeron          TAACAGTCCTACGTGATCTGAGTTCAGACCGGAGTAATCCAGGTCGGTTTCTATCTAT-G
EmperorPenguin              TAATAGTCCTACGTGATCTGAGTTCAGACCGGAGCAATCCAGGTCGGTTTCTATCTAT-G
MourningDove                TAACAGTCCTACGTGATCTGAGTTCAGACCGGAGCAATCCAGGTCGGTTTCTATCTAT-G
                            *** ******************************  *************** **** * *

Chicken                     ACACACTCCTCCTAGTACGAAAGGACCGGAGAAGTGGGGTCAATAC-CACTGAGCACACC
Salmon-crestedCockatoo      ATTAACCCTTCCTAGTACGAAAGGACCGGAAAGGTAGGGCCAATAC-CCCA-AGCACGCC
ScarletMacaw                ACCAACCTTCCCCAGTACGAAAGGACCGGAAAGGTGGGGCCAATAC-TCCA-AGCACGCC
CommonCanary                ATGAACTCTTCCCAGTACGAAAGGATAGGAAAAGTGAGGCCAATAC-TACA-AGCAAGCC
CommonRaven                 ACGAACTCTTCCCAGTACGAAAGGACAGGAAAAGTGAGGCCAATAC-TACA-GGCAAGCC
White-tailedEagle           TAATACCTTCCCTAGTACGAAAGGACCGGGAAAGTAAGGCCAATAC-CACA-GGCACGCC
AfricanOstrich              CTATACTTTTCTCAGTACGAAAGGACCAGAAAAGTGAGGCCAATAC-CAAA-AGCACGCC
PeregrineFalcon             ATAAACCTTCCCCAGTACGAAAGGACCGGAAAGGTGGGGCCAATACTCCCC-AGCACGCC
SnowyOwl                    CTGGACCCTTCCTAGTACGAAAGGACCGGAAGAGTGAGGCCTATAC-CACATAGCACGCC
White-belliedHeron          ATGAACTTTCCCTAGTACGAAAGGACCGGGAAAGTGAGGCCAATAC-CACA-AGCACGCC
EmperorPenguin              ACAAACTTTTCCCAGTACGAAAGGACCGGAAAAGTGAGGCCCATAC-CACA-AGCACGCC
MourningDove                ATGAACTGTTCCTAGTACGAAAGGATCGGAAAAGTGAGGCCAATACTTTTA-TGCACGCC
                                **    *  ************   *    **  ** * ****       ***  **

Chicken                     CCAACCTTCTAAGCAATGAATACAACTCAACTGC-CAAGAACCCCTCCCCCACACCCAAC
Salmon-crestedCockatoo      C--TCATCTCAAGTGATGACTCCAACTAAATCAC-TAAAAGCCCACACCTACATCCC---
ScarletMacaw                CC-CTCCCCCAAGTGATGCCCCCCACTAAATCAC-CAAAGGACCACCCCCACTACCCCAA
CommonCanary                T--TCGCCTTAAGTAATGAAACCAACTTAATTAC--AAAAGGCTATCACACCACACCACG
CommonRaven                 T--TCGCTTTAAGTAATGAATCCAACTAAATTAC-GAAAAGCTATCACACTACAACCATG
White-tailedEagle           T--TCTCCCCAAATAATGACCCCAACTAAATTATAAAAGGAGCCCCATGTAAACCCAAAG
AfricanOstrich              TC-CCCGCCTAATTAGTGAAAACATCTCAACTAACAAGGAAACCACCACCCCCGACC---
PeregrineFalcon             CC-CCTCCCCAAGCAATGACCTCAACTAAACTGCTCAAAGGATTACCCACCCCAAAC---
SnowyOwl                    ---TCCAAAAAAATAATGAATGCAACTCAATTACCAA------CACCCATATTCACC---
White-belliedHeron          ---TCTCCCTAAGTAATGAACCCAACTAAATTAC-CAAAAGGCCACCCATCCTCTTC--G
EmperorPenguin              ---TCCCCCCAAGTAGTGAACCCAACTGAACTACCAAACAGGCCACCCATCTCCACA---
MourningDove                T--CCTCTCTAAGTGATGACTACAACTAAACCAC-CAAGAGACCTCCCACAACACCC-AG
                                      **    **    *  ** **      *                       

Chicken                     TCCTAGAAAAGGATCCA
Salmon-crestedCockatoo      CTCTAGAAAAGAGCC--
ScarletMacaw                C----GAAAAGGGTT--
CommonCanary                TCCAAGAAAAGGACCA-
CommonRaven                 TCCTAGAAAAGGACCA-
White-tailedEagle           CCCTAGAAAAGGGCC--
AfricanOstrich              --CTAGAAAAGGGCTA-
PeregrineFalcon             CCCTAAAAAAGGGCC--
SnowyOwl                    --CTAGACAAGGGCA--
White-belliedHeron          CCCTAGACAAGGGCCA-
EmperorPenguin              -------------CCA-
MourningDove                CCCTAGAAAAGGGCC--
                                             
